FROM node:23-alpine as build

WORKDIR /app

# Install necessary packages
RUN apk add --no-cache openjdk21 git bash

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run prebuild

# Ensure gradlew has execute permissions
RUN chmod +x android/gradlew

# Run the Gradle build
RUN cd android && ./gradlew :app:assembleDebug --stacktrace --info