services:
  db:
    image: mongo:8.0.3
    container_name: ar3m-db
    env_file:
      - ./env/mongo.env
    ports: []
    volumes:
      - mongo-data:/data/db
    networks:
      - ar3m-db-network

  server:
    container_name: ar3m-backend
    build: ./backend/
    ports:
      - "8080:8080"
    networks:
      - ar3m-db-network
    volumes:
      - ./env/back.env:/usr/src/app/.env
    depends_on:
      - db

  client_mobile:
    container_name: ar3m-frontend-mobile
    build:
      context: ./frontend/
      dockerfile: Dockerfile.android
      args:
        - EXPO_TOKEN=${EXPO_TOKEN}
    networks:
      - ar3m-frontend-network
    depends_on:
      - server

  client_web:
    container_name: ar3m-frontend-web
    build:
      context: ./frontend/
      dockerfile: Dockerfile
      args:
        - EXPO_TOKEN=${EXPO_TOKEN}
    ports:
      - "8081:8081"
    networks:
      - ar3m-frontend-network
    depends_on:
      - client_mobile

volumes:
  mongo-data:

networks:
  ar3m-db-network:

  ar3m-frontend-network:
    driver: bridge
