# sudo docker-compose -f docker-compose-mongodb.yml up --build

version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: "ar3m-mongodb"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongo-data:/data/db
      - ./backups:/backup

volumes:
  mongo-data:
